alias intellij='nohup bash /opt/intellij/idea-IC-162.1447.26/bin/idea.sh &'
alias dirs='dirs -v'
alias ls='ls -lh --color=auto'
alias discord='nohup /opt/DiscordCanary/./DiscordCanary &'
alias kraken='nohup /opt/GitKraken/./gitkraken &'
alias clion='nohup /opt/clion-2016.2.2/bin/./clion.sh &'
alias spring='nohup /opt/sts-bundle/sts-3.8.2.RELEASE/./STS &'
